rust-math/fftw

Cargo.toml, src/bin/main.rs, src/complex.rs, src/lib.rs, src/plan.rs
- introduce newtype `c64` wrapping `fftw_complex`
- `Plan` for c2c
=> Complex to Complex Transform

.travis.yml, Cargo.toml, README.md, fftw-sys/Cargo.toml, fftw-sys/src/lib.rs
=> Add switch to enable system library

Cargo.toml, fftw-sys/src/lib.rs, src/bin/main.rs, src/pair.rs, src/plan.rs, src/raw_vec.rs, tests/r2r.rs
=> 32bit interface

Cargo.toml, fftw-src/build.rs, fftw-sys/Cargo.toml, fftw-sys/src/lib.rs, rustfmt.toml, src/pair.rs, src/plan.rs, src/raw_vec.rs, tests/c2c.rs, tests/r2c.rs, tests/r2r.rs
=> Use fftwf_execute and fftwf_destroy_plan

Cargo.toml, src/plan.rs
=> Support 2d/3d in raw-interface

.travis.yml, Cargo.toml, README.md, fftw-sys/Cargo.toml
Experimental issue to use https://github.com/termoshtt/rust-intel-mkl
=> Intel MKL backend

src/aligned_vec.rs, src/lib.rs, src/pair.rs, src/plan.rs
Resolve #8 by implementing `Deref` to slice.
=> Rename RawVec -> AlingedVec

fftw-src/build.rs, fftw-src/fftw-3.3.6-pl1.tar.gz.md5
Related to #31 and #30 
Replace `wget` to `curl`
=> Refactor fftw-sys/build.rs

Cargo.toml, examples/r2r.rs, src/aligned_vec.rs, src/error.rs, src/lib.rs, src/pair.rs, src/plan.rs, src/util.rs, tests/c2c.rs, tests/r2c.rs, tests/r2r.rs
=> Safe interface for 2D/3D transformation using ndarray

src/c2c.rs, src/lib.rs, src/pair.rs, src/plan.rs, src/r2c.rs, src/r2r.rs
Ready for adding 2D/3D interface
=> Split configs

.travis.yml, coverage.sh, fftw-src/build.rs
=> Coverage Report using codecov.io

.gitignore, src/error.rs, src/lib.rs, src/nae.rs, tests/nae.rs
Resolve #43 
Implement an interface for "new-array execution" functions
http://www.fftw.org/fftw3_doc/New_002darray-Execute-Functions.html#New_002darray-Execute-Functions
=> New-Array Execution functions

src/array.rs, src/error.rs, src/lib.rs, src/plan.rs, tests/c2c_aligned.rs, tests/r2c_aligned.rs
Assume the alignment of input/output arrays
=> Plan::aligned

.github/workflows/rust.yml
=> Add macOS feature=system to CI

fftw-src/CHANGELOG.md, fftw-sys/CHANGELOG.md, fftw/CHANGELOG.md
Rendered:
- [fftw](https://github.com/rust-math/fftw/blob/changelog/fftw/CHANGELOG.md)
- [fftw-sys](https://github.com/rust-math/fftw/blob/changelog/fftw-sys/CHANGELOG.md)
- [fftw-src](https://github.com/rust-math/fftw/blob/changelog/fftw-src/CHANGELOG.md)
=> Write CHANGELOG.md

fftw-src/Cargo.toml, fftw-src/build.rs
Some cleanups and partly fix https://github.com/rust-math/fftw/issues/89. Although it's not clear how to best handle Windows. Maybe a new issue should be opened for that.
=> Improve fftw-src build.rs

.gitignore, fftw-src/Cargo.toml, fftw-src/build.rs
Build artifact should not be placed in main source directory.
=> Build FFTW in OUT_DIR

fftw/Cargo.toml, fftw/src/error.rs
- num-complex 0.3.0
- ndarray 0.13.1
- Replace failure to thiserror
=> Upgrade dependencies in fftw

README.md
I fixed a few grammatical problems and improved the readme so that it hopefully looks more professional.
=> Update the grammar and the language of README.md

.github/workflows/rust.yml
An ad-hoc fix for #102  like https://github.com/rust-ndarray/ndarray-linalg/pull/231
=> Disable doctest for Windows

fftw/CHANGELOG.md, fftw/Cargo.toml
https://github.com/rust-ndarray/ndarray/releases/tag/0.14.0
=> Update ndarray to 0.14.0

.github/workflows/rust.yml, fftw-sys/Cargo.toml
Fix intel-mkl-src issue in #120
=> Upgrade intel-mkl-src 0.8.1

fftw-src/Cargo.toml, fftw-sys/Cargo.toml, fftw/Cargo.toml
- ndarray 0.15
- num-complex 0.4
- bitflags 2
and other compatible changes
=> cargo upgrade --incompatible
